NEWS-1/NEWS/NEWS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from news_app import views
from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_app.urls')),
    path('api/v1/',include("api.urls")),
    path('news-admin/', include('blog_app.urls'), name='news-admin'),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('summernote/', include('django_summernote.urls'))]

NEWS-1/NEWS/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns += router.urls

NEWS-1/NEWS/blog_app/urls.py
from django.urls import path
from blog_app import views

app_name = "news_admin"


urlpatterns = [
    path('', views.PostListView.as_view(), name="post-list"),
    path("post_details/<int:pk>/", views.PostDetailView.as_view(), name="post-details"),
    path("draft-list/", views.DraftListView.as_view(), name="draft-list"),
    path("draft_details/<int:pk>/", views.DraftDetailView.as_view(), name="draft-details"),
    path("draft_publish/<int:pk>/", views.DraftPublishView.as_view(), name="draft-publish"),
    path("post-delete/<int:pk>/", views.DeleteView.as_view(), name="post-delete"),
    path("post-create/", views.PostCreateView.as_view(), name="post-create"),
    path("post-update/<int:pk>/", views.PostupdateView.as_view(), name="post-update"),
    path(
        "post-list/",
        views.AllPostListView.as_view(),
        name="all-post-list",
    ),

    path(
        "tag-list/",
        views.TagListView.as_view(),
        name="tag-list",
    ),
    path(
        "category-list/",
        views.CategoryListView.as_view(),
        name="category-list",
    ),
    path(
        "post-list/",
        views.AllPostListView.as_view(),
        name="all-post-list",
    ),
    path(
        "tag-create/",
        views.TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tag-update/<int:pk>/",
        views.TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tag-delete/<int:pk>/",
        views.TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "category-create/",
        views.CategoryCreateView.as_view(),
        name="category-create",
    ),
    path(
        "category-update/<int:pk>/",
        views.CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "category-delete/<int:pk>/",
        views.CategoryDeleteView.as_view(),
        name="category-delete",
    ),
]

NEWS-1/NEWS/templates/news_admin/base.html
{% load static %}



<<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Blog</title>
    <link href="{% static "news_admin/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "news_admin/css/blog.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
</head>
<body>
<div class="container">
    <div class="page-head" style="background-color: #9BD0B5; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="text-decoration: none; display: flex; align-items: center;">
            <div style="color: black;">
                <img src="{% static "img/favicon.ico" %}" alt="Personal blog" width="150px" style="margin-right: 10px;">
            </div>
            <span style="color: black; font-size: 40px;">My Personal Blog</span>
        </a>
{% if user.is_authenticated %}
<form method="post" action="{% url "logout" %}">
  {% csrf_token %}
  <button type="submit">
    <span class="material-symbols-outlined lg-icons">logout</span>
  </button>

</form>
  <a href="{% url "news_admin:draft-list" %}"><span class="material-symbols-outlined lg-icons" style="margin-right: 150px;">drafts</span></a>
  <a href="{% url "news_admin:post-create" %}"><span class="material-symbols-outlined lg-icons" style="margin-left: -300px;">add</span></a>

  {% else %}
  <a href="{% url "login" %}" class="top-menu"> <span class="material-symbols-outlined lg-icons">login</span></a>
{% endif %}


    </div>
    {% block content %}

    {% endblock %}
</div>
<script src="{% static "news_admin/js/bootstrap_bundle.min.js" %}"></script>
</body>
</html>

NEWS-1/NEWS/templates/news_admin/draft_details.html
{% extends "news_admin/base.html" %}

{% block content %}

<div class="row">
    <div class="column">
        <div class="post">
            {% if request.user.is_authenticated %}
            <a href="{% url "news_admin:draft-publish" posts.pk %}" class="btn btn-success">Publish</a>

            <h1>
               {{ posts.title }}
            </h1>
            <div class="date-author">@{{ post.author.username }}</div>
            <p>{{ posts.content }}</p>
            {% endif %}

            {% if request.user.is_authenticated %}
                <a href="{% url "news_admin:post-update" posts.pk %}" class="btn btn-success">Edit</a>
                <a href="{% url "news_admin:post-delete" posts.pk %}" class="btn btn-danger">Delete</a>
                {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

NEWS-1/NEWS/templates/news_admin/draft_list.html
{% extends "news_admin/base.html" %}

{% block content %}

<div class="row">
    <div class="column">
        {% for post in posts %}
        <div class="post">
            <h1>
               <a href="{% url "draft-details" post.pk %}">{{ post.title }}</a>
            </h1>
            <div class="date-author">@{{ post.author.username }}</div>
            <p>{{ post.content | truncatechars:100 }}</p>
        </div>
        {% endfor %}
    </div>  
</div>

{% endblock content %}

NEWS-1/NEWS/templates/news_admin/post_details.html
{% extends "news_admin/base.html" %}



{% block content %}

<div class="row">
    <div class="column">
        <div class="posts">
            <div class="date">{{posts.published_at}}</div>
            <h1>
               <a href=""> {{posts.title}}<a/>
            </h1>
            <div class="date-author">@{{posts.author.username}}</div>
            <p>{{posts.content}}</P>
                {% if request.user.is_authenticated %}
                <a href="{% url 'post-update' posts.pk %}" class="btn btn-success">Edit</a>
                <a href="{% url 'post-delete' posts.pk %}" class="btn btn-danger">Delete</a>
                {% endif %}

            
            
        </div>
    </div>  
</div>

{% endblock content %}

NEWS-1/NEWS/templates/news_admin/post_list.html
{% extends "news_admin/base.html" %}



{% block content %}

<div class="row">
    <div class="column">
        {% for post in posts  %}
        <div class="post">
            <div class="date">{{post.published_at}}</div>
            <h1>
               <a href="{% url "news_admin:post-details" post.pk %}"> {{post.title}}<a/>
            </h1>
            <div class="date-author">@{{post.author.username}}</div>
            <p>{{post.content | truncatechars:100}}</P>
        </div>
        {% endfor %}
    </div>  
</div>

{% endblock content %}